### ISSUE TITLE
Remove unnecessary files

### ISSUE THREAD

**Issue by rohithasrk** [yashagrawal3/BulletinBoard#1]
There are unnecessary files like the ones with extensions pyc, swp, swo etc. Delete all of them and add a way to ignore them permanently. Doesn't look good

**Comment by yell0wfl4sh** [comment]
Added a .gitignore file and removed unnecessary files. Thanks for Review.  :smiley:

**Comment by rohithasrk** [comment]
Anytime. Seems good now. :+1:
